name: Build Hugo site
on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-pdf:
    name: Build PDF files
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -qy texlive

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Build PDF files
        run: make pdf

      - name: Upload PDF files as artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          if-no-files-found: error
          name: pdf
          path: content/cours/*/ressources/*.pdf

  build-site:
    name: Build Hugo site
    runs-on: ubuntu-latest
    needs: build-pdf

    steps:
      - name: Install dependencies
        run: |
          readonly DEB_FILE="hugo_extended_${{ vars.HUGO_VERSION }}_linux-amd64.deb"

          wget https://github.com/gohugoio/hugo/releases/download/v${{ vars.HUGO_VERSION }}/${DEB_FILE}
          sudo dpkg -i "${DEB_FILE}"

      - name: Download PDF files
        uses: actions/download-artifact@v4.1.8
        with:
          name: pdf
          path: pdf

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          path: ccourses

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5.0.0

      - name: Setup PDF files
        run: |
          for pdf in pdf/*; do
            cp -r "${pdf}" ccourses/content/cours
          done

      - name: Download theme
        run: make -C ccourses theme

      - name: Build with Hugo
        run: make -C ccourses BASE_URL="${{ steps.pages.outputs.base_url }}" site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ccourses/public
