name: Deploy Hugo site to GitHub Pages
on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build-pdf:
    name: Build PDF files
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -qy inkscape texlive-full

      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Build PDF files
        run: make pdf

      - name: Upload PDF files as artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          if-no-files-found: error
          name: pdf
          path: content/cours/*/ressources/*.pdf

  build-site:
    name: Build Hugo site
    runs-on: ubuntu-latest
    needs: build-pdf

    steps:
      - name: Install dependencies
        run: |
          readonly DEB_FILE="hugo_extended_${{ vars.HUGO_VERSION }}_linux-amd64.deb"

          wget https://github.com/gohugoio/hugo/releases/download/v${{ vars.HUGO_VERSION }}/${DEB_FILE}
          sudo dpkg -i "${DEB_FILE}"

      - name: Download PDF files
        uses: actions/download-artifact@v4.1.8
        with:
          name: pdf
          path: pdf

      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          path: ccourses

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5.0.0

      - name: Setup PDF files
        run: |
          for pdf in pdf/*; do
            cp -r "${pdf}" ccourses/content/cours
          done

      - name: Download theme
        run: make -C ccourses theme

      - name: Avoid rebuilding PDF files again
        run: sed -i "/^site:/ s/pdf//" ccourses/Makefile

      - name: Build with Hugo
        run: make -C ccourses BASE_URL="${{ steps.pages.outputs.base_url }}" site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ccourses/public

  deploy:
    name: Deploy Hugo site to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-site
    if: github.ref_name == 'main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Hugo site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
